'use strict';
// Ciudad de respaldo para proveedores no residentes: la capital del país (código PAIS ISO 3166-1 de 2 letras)
// y la división (departamento/estado/provincia) donde está. Se usa cuando el Excel no trae la ciudad.
// Incluye todos los países y territorios habitados con código ISO (más XK, Kosovo).
const CAPITALES = {
  AD: { ciudad: 'Andorra la Vella', departamento: 'Andorra la Vella' },
  AE: { ciudad: 'Abu Dabi', departamento: 'Abu Dabi' },
  AF: { ciudad: 'Kabul', departamento: 'Kabul' },
  AG: { ciudad: "Saint John's", departamento: 'Saint John' },
  AI: { ciudad: 'The Valley', departamento: 'Anguila' },
  AL: { ciudad: 'Tirana', departamento: 'Tirana' },
  AM: { ciudad: 'Ereván', departamento: 'Ereván' },
  AO: { ciudad: 'Luanda', departamento: 'Luanda' },
  AR: { ciudad: 'Buenos Aires', departamento: 'Ciudad Autónoma de Buenos Aires' },
  AS: { ciudad: 'Pago Pago', departamento: 'Tutuila' },
  AT: { ciudad: 'Viena', departamento: 'Viena' },
  AU: { ciudad: 'Canberra', departamento: 'Territorio de la Capital Australiana' },
  AW: { ciudad: 'Oranjestad', departamento: 'Aruba' },
  AX: { ciudad: 'Mariehamn', departamento: 'Åland' },
  AZ: { ciudad: 'Bakú', departamento: 'Bakú' },
  BA: { ciudad: 'Sarajevo', departamento: 'Federación de Bosnia y Herzegovina' },
  BB: { ciudad: 'Bridgetown', departamento: 'Saint Michael' },
  BD: { ciudad: 'Daca', departamento: 'Daca' },
  BE: { ciudad: 'Bruselas', departamento: 'Bruselas-Capital' },
  BF: { ciudad: 'Uagadugú', departamento: 'Centro' },
  BG: { ciudad: 'Sofía', departamento: 'Sofía' },
  BH: { ciudad: 'Manama', departamento: 'Capital' },
  BI: { ciudad: 'Gitega', departamento: 'Gitega' },
  BJ: { ciudad: 'Porto Novo', departamento: 'Ouémé' },
  BL: { ciudad: 'Gustavia', departamento: 'San Bartolomé' },
  BM: { ciudad: 'Hamilton', departamento: 'Pembroke' },
  BN: { ciudad: 'Bandar Seri Begawan', departamento: 'Brunéi-Muara' },
  BO: { ciudad: 'Sucre', departamento: 'Chuquisaca' },
  BQ: { ciudad: 'Kralendijk', departamento: 'Bonaire' },
  BR: { ciudad: 'Brasília', departamento: 'Distrito Federal' },
  BS: { ciudad: 'Nasáu', departamento: 'Nueva Providencia' },
  BT: { ciudad: 'Timbu', departamento: 'Timbu' },
  BW: { ciudad: 'Gaborone', departamento: 'Sudeste' },
  BY: { ciudad: 'Minsk', departamento: 'Minsk' },
  BZ: { ciudad: 'Belmopán', departamento: 'Cayo' },
  CA: { ciudad: 'Ottawa', departamento: 'Ontario' },
  CC: { ciudad: 'West Island', departamento: 'Islas Cocos' },
  CD: { ciudad: 'Kinsasa', departamento: 'Kinsasa' },
  CF: { ciudad: 'Bangui', departamento: 'Bangui' },
  CG: { ciudad: 'Brazzaville', departamento: 'Brazzaville' },
  CH: { ciudad: 'Berna', departamento: 'Berna' },
  CI: { ciudad: 'Yamusukro', departamento: 'Yamusukro' },
  CK: { ciudad: 'Avarua', departamento: 'Rarotonga' },
  CL: { ciudad: 'Santiago', departamento: 'Región Metropolitana' },
  CM: { ciudad: 'Yaundé', departamento: 'Centro' },
  CN: { ciudad: 'Pekín', departamento: 'Pekín' },
  CR: { ciudad: 'San José', departamento: 'San José' },
  CU: { ciudad: 'La Habana', departamento: 'La Habana' },
  CV: { ciudad: 'Praia', departamento: 'Santiago' },
  CW: { ciudad: 'Willemstad', departamento: 'Curazao' },
  CX: { ciudad: 'Flying Fish Cove', departamento: 'Isla de Navidad' },
  CY: { ciudad: 'Nicosia', departamento: 'Nicosia' },
  CZ: { ciudad: 'Praga', departamento: 'Praga' },
  DE: { ciudad: 'Berlín', departamento: 'Berlín' },
  DJ: { ciudad: 'Yibuti', departamento: 'Yibuti' },
  DK: { ciudad: 'Copenhague', departamento: 'Capital' },
  DM: { ciudad: 'Roseau', departamento: 'Saint George' },
  DO: { ciudad: 'Santo Domingo', departamento: 'Distrito Nacional' },
  DZ: { ciudad: 'Argel', departamento: 'Argel' },
  EC: { ciudad: 'Quito', departamento: 'Pichincha' },
  EE: { ciudad: 'Tallin', departamento: 'Harju' },
  EG: { ciudad: 'El Cairo', departamento: 'El Cairo' },
  EH: { ciudad: 'El Aaiún', departamento: 'Sahara Occidental' },
  ER: { ciudad: 'Asmara', departamento: 'Maekel' },
  ES: { ciudad: 'Madrid', departamento: 'Madrid' },
  ET: { ciudad: 'Adís Abeba', departamento: 'Adís Abeba' },
  FI: { ciudad: 'Helsinki', departamento: 'Uusimaa' },
  FJ: { ciudad: 'Suva', departamento: 'Central' },
  FK: { ciudad: 'Stanley', departamento: 'Islas Malvinas' },
  FM: { ciudad: 'Palikir', departamento: 'Pohnpei' },
  FO: { ciudad: 'Tórshavn', departamento: 'Streymoy' },
  FR: { ciudad: 'París', departamento: 'Isla de Francia' },
  GA: { ciudad: 'Libreville', departamento: 'Estuaire' },
  GB: { ciudad: 'Londres', departamento: 'Inglaterra' },
  GD: { ciudad: "Saint George's", departamento: 'Saint George' },
  GE: { ciudad: 'Tiflis', departamento: 'Tiflis' },
  GF: { ciudad: 'Cayena', departamento: 'Guayana Francesa' },
  GG: { ciudad: 'Saint Peter Port', departamento: 'Guernsey' },
  GH: { ciudad: 'Acra', departamento: 'Gran Acra' },
  GI: { ciudad: 'Gibraltar', departamento: 'Gibraltar' },
  GL: { ciudad: 'Nuuk', departamento: 'Sermersooq' },
  GM: { ciudad: 'Banjul', departamento: 'Banjul' },
  GN: { ciudad: 'Conakri', departamento: 'Conakri' },
  GP: { ciudad: 'Basse-Terre', departamento: 'Guadalupe' },
  GQ: { ciudad: 'Malabo', departamento: 'Bioko Norte' },
  GR: { ciudad: 'Atenas', departamento: 'Ática' },
  GT: { ciudad: 'Ciudad de Guatemala', departamento: 'Guatemala' },
  GU: { ciudad: 'Hagåtña', departamento: 'Guam' },
  GW: { ciudad: 'Bisáu', departamento: 'Bisáu' },
  GY: { ciudad: 'Georgetown', departamento: 'Demerara-Mahaica' },
  HK: { ciudad: 'Hong Kong', departamento: 'Hong Kong' },
  HN: { ciudad: 'Tegucigalpa', departamento: 'Francisco Morazán' },
  HR: { ciudad: 'Zagreb', departamento: 'Zagreb' },
  HT: { ciudad: 'Puerto Príncipe', departamento: 'Oeste' },
  HU: { ciudad: 'Budapest', departamento: 'Budapest' },
  ID: { ciudad: 'Yakarta', departamento: 'Yakarta' },
  IE: { ciudad: 'Dublín', departamento: 'Leinster' },
  IL: { ciudad: 'Jerusalén', departamento: 'Jerusalén' },
  IM: { ciudad: 'Douglas', departamento: 'Isla de Man' },
  IN: { ciudad: 'Nueva Delhi', departamento: 'Delhi' },
  IQ: { ciudad: 'Bagdad', departamento: 'Bagdad' },
  IR: { ciudad: 'Teherán', departamento: 'Teherán' },
  IS: { ciudad: 'Reikiavik', departamento: 'Región de la Capital' },
  IT: { ciudad: 'Roma', departamento: 'Lacio' },
  JE: { ciudad: 'Saint Helier', departamento: 'Jersey' },
  JM: { ciudad: 'Kingston', departamento: 'Kingston' },
  JO: { ciudad: 'Amán', departamento: 'Amán' },
  JP: { ciudad: 'Tokio', departamento: 'Tokio' },
  KE: { ciudad: 'Nairobi', departamento: 'Nairobi' },
  KG: { ciudad: 'Biskek', departamento: 'Biskek' },
  KH: { ciudad: 'Nom Pen', departamento: 'Nom Pen' },
  KI: { ciudad: 'Tarawa Sur', departamento: 'Islas Gilbert' },
  KM: { ciudad: 'Moroni', departamento: 'Gran Comora' },
  KN: { ciudad: 'Basseterre', departamento: 'Saint George Basseterre' },
  KP: { ciudad: 'Pionyang', departamento: 'Pionyang' },
  KR: { ciudad: 'Seúl', departamento: 'Seúl' },
  KW: { ciudad: 'Kuwait', departamento: 'Capital' },
  KY: { ciudad: 'George Town', departamento: 'Gran Caimán' },
  KZ: { ciudad: 'Astaná', departamento: 'Astaná' },
  LA: { ciudad: 'Vientián', departamento: 'Vientián' },
  LB: { ciudad: 'Beirut', departamento: 'Beirut' },
  LC: { ciudad: 'Castries', departamento: 'Castries' },
  LI: { ciudad: 'Vaduz', departamento: 'Vaduz' },
  LK: { ciudad: 'Sri Jayawardenepura Kotte', departamento: 'Occidental' },
  LR: { ciudad: 'Monrovia', departamento: 'Montserrado' },
  LS: { ciudad: 'Maseru', departamento: 'Maseru' },
  LT: { ciudad: 'Vilna', departamento: 'Vilna' },
  LU: { ciudad: 'Luxemburgo', departamento: 'Luxemburgo' },
  LV: { ciudad: 'Riga', departamento: 'Riga' },
  LY: { ciudad: 'Trípoli', departamento: 'Trípoli' },
  MA: { ciudad: 'Rabat', departamento: 'Rabat-Salé-Kenitra' },
  MC: { ciudad: 'Mónaco', departamento: 'Mónaco' },
  MD: { ciudad: 'Chisináu', departamento: 'Chisináu' },
  ME: { ciudad: 'Podgorica', departamento: 'Podgorica' },
  MF: { ciudad: 'Marigot', departamento: 'San Martín' },
  MG: { ciudad: 'Antananarivo', departamento: 'Analamanga' },
  MH: { ciudad: 'Majuro', departamento: 'Majuro' },
  MK: { ciudad: 'Skopie', departamento: 'Skopie' },
  ML: { ciudad: 'Bamako', departamento: 'Bamako' },
  MM: { ciudad: 'Naipyidó', departamento: 'Naipyidó' },
  MN: { ciudad: 'Ulán Bator', departamento: 'Ulán Bator' },
  MO: { ciudad: 'Macao', departamento: 'Macao' },
  MP: { ciudad: 'Saipán', departamento: 'Saipán' },
  MQ: { ciudad: 'Fort-de-France', departamento: 'Martinica' },
  MR: { ciudad: 'Nuakchot', departamento: 'Nuakchot' },
  MS: { ciudad: 'Plymouth', departamento: 'Montserrat' },
  MT: { ciudad: 'La Valeta', departamento: 'La Valeta' },
  MU: { ciudad: 'Port Louis', departamento: 'Port Louis' },
  MV: { ciudad: 'Malé', departamento: 'Malé' },
  MW: { ciudad: 'Lilongüe', departamento: 'Central' },
  MX: { ciudad: 'Ciudad de México', departamento: 'Ciudad de México' },
  MY: { ciudad: 'Kuala Lumpur', departamento: 'Kuala Lumpur' },
  MZ: { ciudad: 'Maputo', departamento: 'Maputo' },
  NA: { ciudad: 'Windhoek', departamento: 'Khomas' },
  NC: { ciudad: 'Numea', departamento: 'Provincia Sur' },
  NE: { ciudad: 'Niamey', departamento: 'Niamey' },
  NF: { ciudad: 'Kingston', departamento: 'Isla Norfolk' },
  NG: { ciudad: 'Abuya', departamento: 'Territorio de la Capital Federal' },
  NI: { ciudad: 'Managua', departamento: 'Managua' },
  NL: { ciudad: 'Ámsterdam', departamento: 'Holanda Septentrional' },
  NO: { ciudad: 'Oslo', departamento: 'Oslo' },
  NP: { ciudad: 'Katmandú', departamento: 'Bagmati' },
  NR: { ciudad: 'Yaren', departamento: 'Yaren' },
  NU: { ciudad: 'Alofi', departamento: 'Niue' },
  NZ: { ciudad: 'Wellington', departamento: 'Wellington' },
  OM: { ciudad: 'Mascate', departamento: 'Mascate' },
  PA: { ciudad: 'Ciudad de Panamá', departamento: 'Panamá' },
  PE: { ciudad: 'Lima', departamento: 'Lima' },
  PF: { ciudad: 'Papeete', departamento: 'Tahití' },
  PG: { ciudad: 'Port Moresby', departamento: 'Distrito de la Capital Nacional' },
  PH: { ciudad: 'Manila', departamento: 'Gran Manila' },
  PK: { ciudad: 'Islamabad', departamento: 'Territorio de la Capital de Islamabad' },
  PL: { ciudad: 'Varsovia', departamento: 'Mazovia' },
  PM: { ciudad: 'Saint-Pierre', departamento: 'San Pedro y Miquelón' },
  PN: { ciudad: 'Adamstown', departamento: 'Islas Pitcairn' },
  PR: { ciudad: 'San Juan', departamento: 'San Juan' },
  PS: { ciudad: 'Ramala', departamento: 'Cisjordania' },
  PT: { ciudad: 'Lisboa', departamento: 'Lisboa' },
  PW: { ciudad: 'Melekeok', departamento: 'Melekeok' },
  PY: { ciudad: 'Asunción', departamento: 'Distrito Capital' },
  QA: { ciudad: 'Doha', departamento: 'Doha' },
  RE: { ciudad: 'Saint-Denis', departamento: 'Reunión' },
  RO: { ciudad: 'Bucarest', departamento: 'Bucarest' },
  RS: { ciudad: 'Belgrado', departamento: 'Belgrado' },
  RU: { ciudad: 'Moscú', departamento: 'Moscú' },
  RW: { ciudad: 'Kigali', departamento: 'Kigali' },
  SA: { ciudad: 'Riad', departamento: 'Riad' },
  SB: { ciudad: 'Honiara', departamento: 'Honiara' },
  SC: { ciudad: 'Victoria', departamento: 'Mahé' },
  SD: { ciudad: 'Jartum', departamento: 'Jartum' },
  SE: { ciudad: 'Estocolmo', departamento: 'Estocolmo' },
  SG: { ciudad: 'Singapur', departamento: 'Singapur' },
  SH: { ciudad: 'Jamestown', departamento: 'Santa Elena' },
  SI: { ciudad: 'Liubliana', departamento: 'Liubliana' },
  SJ: { ciudad: 'Longyearbyen', departamento: 'Svalbard' },
  SK: { ciudad: 'Bratislava', departamento: 'Bratislava' },
  SL: { ciudad: 'Freetown', departamento: 'Área Occidental' },
  SM: { ciudad: 'San Marino', departamento: 'San Marino' },
  SN: { ciudad: 'Dakar', departamento: 'Dakar' },
  SO: { ciudad: 'Mogadiscio', departamento: 'Banaadir' },
  SR: { ciudad: 'Paramaribo', departamento: 'Paramaribo' },
  SS: { ciudad: 'Yuba', departamento: 'Ecuatoria Central' },
  ST: { ciudad: 'Santo Tomé', departamento: 'Água Grande' },
  SV: { ciudad: 'San Salvador', departamento: 'San Salvador' },
  SX: { ciudad: 'Philipsburg', departamento: 'Sint Maarten' },
  SY: { ciudad: 'Damasco', departamento: 'Damasco' },
  SZ: { ciudad: 'Mbabane', departamento: 'Hhohho' },
  TC: { ciudad: 'Cockburn Town', departamento: 'Gran Turca' },
  TD: { ciudad: 'Yamena', departamento: 'Yamena' },
  TF: { ciudad: 'Port-aux-Français', departamento: 'Kerguelen' },
  TG: { ciudad: 'Lomé', departamento: 'Marítima' },
  TH: { ciudad: 'Bangkok', departamento: 'Bangkok' },
  TJ: { ciudad: 'Dusambé', departamento: 'Dusambé' },
  TK: { ciudad: 'Fakaofo', departamento: 'Tokelau' },
  TL: { ciudad: 'Dili', departamento: 'Dili' },
  TM: { ciudad: 'Asjabad', departamento: 'Asjabad' },
  TN: { ciudad: 'Túnez', departamento: 'Túnez' },
  TO: { ciudad: 'Nukualofa', departamento: 'Tongatapu' },
  TR: { ciudad: 'Ankara', departamento: 'Ankara' },
  TT: { ciudad: 'Puerto España', departamento: 'Puerto España' },
  TV: { ciudad: 'Funafuti', departamento: 'Funafuti' },
  TW: { ciudad: 'Taipéi', departamento: 'Taipéi' },
  TZ: { ciudad: 'Dodoma', departamento: 'Dodoma' },
  UA: { ciudad: 'Kiev', departamento: 'Kiev' },
  UG: { ciudad: 'Kampala', departamento: 'Central' },
  US: { ciudad: 'Washington', departamento: 'District of Columbia' },
  UY: { ciudad: 'Montevideo', departamento: 'Montevideo' },
  UZ: { ciudad: 'Taskent', departamento: 'Taskent' },
  VA: { ciudad: 'Ciudad del Vaticano', departamento: 'Ciudad del Vaticano' },
  VC: { ciudad: 'Kingstown', departamento: 'Saint George' },
  VE: { ciudad: 'Caracas', departamento: 'Distrito Capital' },
  VG: { ciudad: 'Road Town', departamento: 'Tórtola' },
  VI: { ciudad: 'Charlotte Amalie', departamento: 'Saint Thomas' },
  VN: { ciudad: 'Hanói', departamento: 'Hanói' },
  VU: { ciudad: 'Port Vila', departamento: 'Shefa' },
  WF: { ciudad: 'Mata-Utu', departamento: 'Uvea' },
  WS: { ciudad: 'Apia', departamento: 'Tuamasaga' },
  XK: { ciudad: 'Pristina', departamento: 'Pristina' },
  YE: { ciudad: 'Saná', departamento: 'Saná' },
  YT: { ciudad: 'Mamoudzou', departamento: 'Mayotte' },
  ZA: { ciudad: 'Pretoria', departamento: 'Gauteng' },
  ZM: { ciudad: 'Lusaka', departamento: 'Lusaka' },
  ZW: { ciudad: 'Harare', departamento: 'Harare' },
};

module.exports = { CAPITALES };
